In [1]:
from __future__ import division  
import numpy as np  
from numpy import linalg
from matplotlib import pyplot as plt
import seaborn as sns; sns.set()
from metodos import *
%matplotlib inline

In [2]:
MAX_ITE = 2000
a = -4
b = 1
c = 1
h = k = 0.25
M = N = 4

# h = k = 0.05
# M = N = 20

# h = k = 0.025
# M = N = 40

# np.diag(a*np.ones((N-1)*(M-1)), k=0)
A = np.zeros(((N-1) * (M-1), (N-1) * (M-1)))
ii = 0
for i in range(1, N):
    for j in range(1, M):
        if i+1 != N:
            A[ii][((i)*(N-1)) + j-1] = 1
        if i-1 != 0:
            A[ii][((i-2)*(N-1)) + j-1] = 1
        A[ii][(i-1)*(N-1) + j-1] = a
        if j+1 != M:
            A[ii][((i-1)*(N-1)) + j] = 1
        if j-1 != 0:
            A[ii][((i-1)*(N-1)) + j - 2] = 1
        ii += 1
    

In [3]:
# for i in range(len(A)):
#     for j in range(len(A)):
#         print(int(A[i,j]), end='\t&\t')
#     print("\\\\")
print(A)

[[-4.  1.  0.  1.  0.  0.  0.  0.  0.]
 [ 1. -4.  1.  0.  1.  0.  0.  0.  0.]
 [ 0.  1. -4.  0.  0.  1.  0.  0.  0.]
 [ 1.  0.  0. -4.  1.  0.  1.  0.  0.]
 [ 0.  1.  0.  1. -4.  1.  0.  1.  0.]
 [ 0.  0.  1.  0.  1. -4.  0.  0.  1.]
 [ 0.  0.  0.  1.  0.  0. -4.  1.  0.]
 [ 0.  0.  0.  0.  1.  0.  1. -4.  1.]
 [ 0.  0.  0.  0.  0.  1.  0.  1. -4.]]


In [4]:
U = np.zeros(((N-1) * (M-1),1))
# for i in range(1, N):
#     for j in range(1, M):
#         print("U_{"+str(i)+","+str(j)+"}\\\\")
    
print(U)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [5]:
r = np.zeros(((N-1) * (M-1), 1))
ii = 0
for i in range(1, N):
    for j in range(1, M):
        if i+1 == N:
            r[ii][0] -= 100
        if i-1 == 0:
            r[ii][0] -= 75
        if j+1 == M:
            r[ii][0] -= 0
        if j-1 == 0:
            r[ii][0] -= 50
        print(ii)
        ii += 1

0
1
2
3
4
5
6
7
8


In [6]:
for j in range(len(r)):
    print(str(int(r[j][0]))+"\\\\")
    
print(r)

-125\\
-75\\
-75\\
-50\\
0\\
0\\
-150\\
-100\\
-100\\
[[-125.]
 [ -75.]
 [ -75.]
 [ -50.]
 [   0.]
 [   0.]
 [-150.]
 [-100.]
 [-100.]]


In [7]:
D = np.diag(np.diag(A))
print(D)

[[-4.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. -4.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. -4.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -4.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -4.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. -4.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. -4.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. -4.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0. -4.]]


In [8]:
S = np.triu(A, k=1)
print(S)

[[0. 1. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [9]:
L = np.tril(A, k=-1)
print(L)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 1. 0.]]


In [10]:
Di = np.linalg.inv(D)
print(Di)

[[-0.25 -0.   -0.   -0.   -0.   -0.   -0.   -0.   -0.  ]
 [-0.   -0.25 -0.   -0.   -0.   -0.   -0.   -0.   -0.  ]
 [-0.   -0.   -0.25 -0.   -0.   -0.   -0.   -0.   -0.  ]
 [-0.   -0.   -0.   -0.25 -0.   -0.   -0.   -0.   -0.  ]
 [-0.   -0.   -0.   -0.   -0.25 -0.   -0.   -0.   -0.  ]
 [-0.   -0.   -0.   -0.   -0.   -0.25 -0.   -0.   -0.  ]
 [-0.   -0.   -0.   -0.   -0.   -0.   -0.25 -0.   -0.  ]
 [-0.   -0.   -0.   -0.   -0.   -0.   -0.   -0.25 -0.  ]
 [-0.   -0.   -0.   -0.   -0.   -0.   -0.   -0.   -0.25]]


In [11]:
Uold = U.copy()
print(Uold)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [12]:
def gera_res(U, M, N):
    u = np.zeros((M+1, N+1))
    for j in range(M, -1, -1):
        for i in range(0, N+1):
            if (i == 0 and j == M) or (i == 0 and j == 0) or (i == N and j == M) or (i == N and j == 0):
                continue
            if j == M:
                u[j][i] = 0
            elif j == 0:
                u[j][i] = 50
            elif i == 0:
                u[j][i] = 75
            elif i == N:
                u[j][i] = 100
            else:
                u[j][i] = U[(i-1)*(N-1) + j-1][0]
    return u
def print_tabela(U, M, N):
    for j in range(M, -1, -1):
        for i in range(0, N+1):
            if (i == 0 and j == M) or (i == 0 and j == 0) or (i == N and j == M) or (i == N and j == 0):
                print("       ", end=' &\t')
                continue
            if j == M:
                print("", 0, "     ", end='&\t')
            elif j == 0:
                print("{:.1f}".format(50), end='\t&\t')
            elif i == 0:
                print("{:.1f}".format(75), end='\t&\t')
            elif i == N:
                print("{:.1f}".format(100), end='')
            else:
    #             print("ij:", i, j, "\n")
                print("{:.4f}".format(U[(i-1)*(N-1) + j-1][0]), end='\t&\t')
        print("\\\\")

# def print_res(u, M, N, h, k, metodo=""):
#     x_ticks = np.linspace(0, 1, int(1/h + 1))
#     y_ticks = np.linspace(0, 1, int(1/k + 1))
#     title = 'Solução Numérica '+ metodo + ' h=' + str(h) + ' k=' + str(k)
#     plt.figure(dpi=200, figsize=(6, 6))
#     plt.title(title)
#     text = [ [ None for y in range( N+1 ) ] for x in range( M+1 ) ] 
#     for i in range(N+1):
#         for j in range(M+1):
#             text[i][j] = r"$U_{"+i+","+j"}$"
#     ax = sns.heatmap(u, cmap='jet', annot=text, fmt ='', cbar_kws={'label': 'Temperatura (ºC)'})
#     ax.set_xticklabels(y_ticks)
#     ax.set_yticklabels(y_ticks)
#     ax.invert_yaxis()
#     plt.show()


In [13]:
# print("Jacobi")
# Ur, ite, error, tempo = jacobi(S, D, L, r, U, 1e-3, MAX_ITE)
# # print_tabela(Ur, M, N)
# # print(Ur)
# print("Iterações: ", ite)
# print("Erro: ", error)
# print("Tempo: ", tempo)
# res = gera_res(Ur, M, N)


In [14]:
# print_res(res, M, N, 0, 1, 1, h, k, metodo="M. de Jacobi", print_annot=False)

In [15]:
# print("Gauss-Seidel:")
# Ur, ite, error, tempo = gauss_seidel(S, D, L, r, U, 1e-3, MAX_ITE)
# # print_tabela(Ur, M, N)
# # print(Ur)
# print("Iterações: ", ite)
# print("Erro: ", error)
# print("Tempo: ", tempo)
# # res = gera_res(Ur, M, N)
# # # print_res(res, M, N, 0, 1, 1, h, k,  metodo="M. de Gauss-Seidel", print_annot=False)

In [16]:
print(np.dot(Di, L+S))
rho = np.max(np.linalg.eigvalsh(np.dot(Di, L+S)))
w = 1 + (rho/(1+np.sqrt(1-rho**2)))**2 
print(w)
w = 2/(1+np.sqrt(1-rho**2)) 
print(w)

print("SOR:")
Ur, ite, error, tempo = SOR(S, D, L, r, U, w, 1e-3, MAX_ITE)
# print_tabela(Ur, M, N)
# print(Ur)
print("Iterações Ótimo: ", ite)
print("Erro: ", error)
print("Tempo: ", tempo)

res = gera_res(Ur, M, N)
# print_res(res, M, N, 0, 1, 1, k, h,  metodo="M. SOR", print_annot=False)

[[ 0.   -0.25  0.   -0.25  0.    0.    0.    0.    0.  ]
 [-0.25  0.   -0.25  0.   -0.25  0.    0.    0.    0.  ]
 [ 0.   -0.25  0.    0.    0.   -0.25  0.    0.    0.  ]
 [-0.25  0.    0.    0.   -0.25  0.   -0.25  0.    0.  ]
 [ 0.   -0.25  0.   -0.25  0.   -0.25  0.   -0.25  0.  ]
 [ 0.    0.   -0.25  0.   -0.25  0.    0.    0.   -0.25]
 [ 0.    0.    0.   -0.25  0.    0.    0.   -0.25  0.  ]
 [ 0.    0.    0.    0.   -0.25  0.   -0.25  0.   -0.25]
 [ 0.    0.    0.    0.    0.   -0.25  0.   -0.25  0.  ]]
1.1715728752538095
1.1715728752538097
SOR:
Iterações Ótimo:  10
Erro:  0.0007715394512477932
Tempo:  0.0025947093963623047


In [24]:
def array_to_bmatrix(array):
    begin = '\\begin{bmatrix} \n'
    data = ''
    for line in array:        
        if line.size == 1:
            if line == 0:
                data = data + ' &'
            else:
                data = data + ' %.2f &'%line
            data = data + r' \\'
            data = data + '\n'
            continue
        for element in line:
            if element == 0:
                data = data + ' &'
            else:
                data = data + ' %.2f &'%element

        data = data + r' \\'
        data = data + '\n'
    end = '\end{bmatrix}'
    print(begin + data + end)



J_t = np.dot(Di, L+S)
# array_to_bmatrix(J_t)
# plt.figure(figsize=(12,12))
# plt.title("Matriz de iteração $G_J$")
# plt.spy(J_t, markersize = 5) 
# plt.show()
autovalores = np.linalg.eigvalsh(J_t)
# array_to_bmatrix(autovalores)
# print(autovalores)
rho = np.max(autovalores)
# print(rho)
w = 1 + (rho/(1+np.sqrt(1-rho**2)))**2 
# print(w)
# w = 2/(1+np.sqrt(1-rho**2)) 
# print(w)
Ur, ite, error, tempo = SOR(S, D, L, r, U, w, 1e-3, MAX_ITE)
print("Iterações: {} - w: {}: ".format(ite, w))
ws = np.linspace(0,2, int(2/0.2)+1)

for w in ws[:]:
    Ur, ite, error, tempo = SOR(S, D, L, r, U, w, 1e-3, MAX_ITE)
    print("Iterações: {} - w: {}: ".format(ite, w))
    print("Erro: ", error)


Iterações: 10 - w: 1.1715728752538095: 
Iterações: 1 - w: 0.0: 
Erro:  0.0
Iterações: 143 - w: 0.2: 
Erro:  0.0009864706625642469
Iterações: 69 - w: 0.4: 
Erro:  0.0009877536087695368
Iterações: 43 - w: 0.6000000000000001: 
Erro:  0.0007763641124537473
Iterações: 28 - w: 0.8: 
Erro:  0.0008124060322300669
Iterações: 18 - w: 1.0: 
Erro:  0.0008717179295661342
Iterações: 10 - w: 1.2000000000000002: 
Erro:  0.00032735738632502445
Iterações: 15 - w: 1.4000000000000001: 
Erro:  0.0006718974698619511
Iterações: 25 - w: 1.6: 
Erro:  0.0008780434232738431
Iterações: 55 - w: 1.8: 
Erro:  0.00081770078758867
Iterações: 2000 - w: 2.0: 
Erro:  269.45660748053825
